### PR TITLE
Resolves #17 "Add configurable User-Agent to Sweble requests"

### LINKED ISSUE #17: Add configurable User-Agent to Sweble requests
We see 

```bash
Failed to create WikiConfig for language for Portuguese, using default instead
java.io.IOException: Server returned HTTP response code: 403 for URL: https://pt.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=namespacealiases&format=xml
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2038)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.getXMLFromUrl(LanguageConfigGenerator.java:341)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.getNamespaceAliases(LanguageConfigGenerator.java:316)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:113)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:82)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:67)
	at org.dkpro.jwpl.api.WikiConstants$Language.getWikiconfig(WikiConstants.java:104)
	at org.dkpro.jwpl.api.WikiConfigTest.testGetWikiConf(WikiConfigTest.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:787)
	at org.junit.platform.commons.support.ReflectionSupport.invokeMethod(ReflectionSupport.java:478)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:161)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:152)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:91)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:112)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:94)
	at 
````

in JWPL.

This is most likely caused by the change on Wiki, which now requires a user agent. We need to add a test in sweble for this + send a configurable user agent with the request.

### PR DESCRIPTION
**Pull request by rzo1**

### CODE REVIEW

File: sweble-wikitext-components-parent/swc-engine/src/main/java/org/sweble/wikitext/engine/utils/LanguageConfigGenerator.java [hunk 1]
```diff
@@ -336,9 +342,24 @@ public static Document getXMLFromUrl(String urlString)
 	{
 		URL url = new URL(urlString);
 		URLConnection connection = url.openConnection();
-		DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
+        connection.setRequestProperty("User-Agent", loadDefaultUserAgent());
+        DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
```
Comment (mawiesne) [inline sweble-wikitext-components-parent/swc-engine/src/main/java/org/sweble/wikitext/engine/utils/LanguageConfigGenerator.java:346]: Indentation looks different here.

**Review by mawiesne — APPROVED** [review]

File: sweble-wikitext-components-parent/swc-engine/src/main/java/org/sweble/wikitext/engine/utils/LanguageConfigGenerator.java (hunk 1 above)
Comment (rzo1) [reply sweble-wikitext-components-parent/swc-engine/src/main/java/org/sweble/wikitext/engine/utils/LanguageConfigGenerator.java:346]: Passes checkstyle :)
